---
name: Install CMake build dependencies
description: Install CMake build dependencies
runs:
    using: composite
    steps:
        - uses: ./.github/actions/install-build-dependencies

        - name: Install CMake dependencies
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  brew install bazelisk ccache cmake zlib
              else
                  # Compiler
                  sudo apt-get install -y bzip2 clang-9 clang++-9 lld-9 tar bzip2 ninja-build tar ninja-build
                  # CMake
                  wget https://github.com/Kitware/CMake/releases/download/v3.20.5/cmake-3.20.5-linux-x86_64.sh -O /tmp/cmake.sh
                  sudo bash /tmp/cmake.sh --prefix=/usr/local --exclude-subdir --skip-license
                  rm /tmp/cmake.sh
                  # protobuf
                  sudo apt-get install autoconf libtool make
                  # Testing
                  sudo apt-get install coreutils
              fi
          shell: bash
